### ISSUE TITLE
not work with accounts-base in meteor 2.10.0

### ISSUE THREAD

**Issue by SvenWangChina** [Akryum/meteor-vite#20] opened 2023-01-16 03:56 UTC
I got the error with accounts-base in meteor 2.10.0,

`Uncaught SyntaxError: Unexpected token 'default' (at accounts-base:17:14)`

**Comment by red-meadow** [comment] 2023-01-16 10:54
Duplicate of #8

**Closed** 2023-01-17 08:50 UTC
